neostudio-team/GridaBoard2

src/GridaBoard/GridaDoc.ts, src/GridaBoard/Load/LoadGrida.tsx, src/GridaBoard/Save/SaveGrida.tsx, src/nl-lib/common/neopdf/NeoPdfDocument.ts
pdf와 stroke를 분리시켜 load시 stroke 배열화로 page마다 올바르게 stroke가 찍힐 수 있게 바꾸고
load시에 stroke를 지워질 수 있게 수정했습니다.
addPage시 page가 0으로 찍히는 것을 방지하기 위해 GridaDoc에 appendPdfDocument에 basePageInfo값을 theBase로 지정했습니다.
=> pdf와 stroke 분리 / load시 stroke 배열화 / addPage page값 에러 수정

src/GridaBoard/GridaDoc.ts, src/GridaBoard/Load/ConvertFileLoad.tsx, src/GridaBoard/View/Drawer/ThumbnailItem.tsx, src/GridaBoard/components/buttons/BoardNewButton.tsx, src/boardList/layout/component/mainContent/MainNewButton.tsx, src/nl-lib/common/util/functions.ts
1. [Feat] 기존 파일 열려진 상태에서 새 파일 불러오거나 DnD할 경우 DocName(타이틀)이 변경되지 않도록 변경
-> 새 파일 불러올 때만 이름 변경
2. [Feat] LeftSideLayer의 썸네일 클릭 시 해당 영역 스크롤도 중앙으로 이동
3. [Feat] 파일 로드 시 활성화된 썸네일로 스크롤 이동
=> [Feat] 불러오기 시 타이틀 미변경 및 스크롤 이동의 건

src/GridaBoard/GridaPage.tsx, src/GridaBoard/store/reducers/gestureReducer.ts, src/nl-lib/common/constants/MapperConstants.ts, src/nl-lib/common/noteserver/SurfaceInfo.ts, src/nl-lib/renderer/penview/PenBasedRenderWorker.tsx, src/nl-lib/renderer/penview/PenBasedRenderer.tsx
부기보드의 '세로모드 사용' -> '가로모드 사용'으로 변경됨에 따라 관련 코드들 업데이트
[업데이트]
1. page mode를 구별하여 rotation을 적용하도록 함. (landscape <-> portrait)
2. Symbol을 위한 reducer 정의
[수정사항]
1. tap stroke가 gesture 가능영역에서만 지워지고 그 외의 영역에서는 지워지지 않도록 수정
2. hide 모드일때 createLiveStroke가 생성되기 전에 함수를 종료시켜 pathObj가 생성되지 않고 이로인해 발생하는 오류 수정
3. 2. gesture reducer 함수들의 리팩토링
[진행사항]
1. symbol 표시를 담당하는 로직 개선중
=> [제스처] 부기보드의 요구사항 변경에 따른 제스쳐 관련 코드 업데이트

src/boardList/BoardListPageFunc.tsx, src/nl-lib/renderer/penview/PenBasedRenderer.tsx
1. 그리다보드 홈으로 이동 시 상태값이 정상적으로 초기화 되지 않던 버그 수정
2. 그리다보드 홈으로 이동 시 NeoSmartPen의 이벤트가 정상적으로 구독취소 되지 않던 버그 수정
=> [버그] 버그 수정 업데이트

src/GridaBoard/KeyBoardShortCut.ts, src/boardList/BoardList.tsx
Fix: 파일 로드 시 그리다보드 리셋하도록 설정
- 페이지 생성 또는 로드 후 새 페이지를 생성할 경우 해당 페이지로 스크롤이 자동이동되며,
setActivePageNo 호출하여 페이지 값 변경하는데, 이후 메인화면으로 이동 시에도 해당 값이 남아
activePage 값이 적은 데이터를 로드하거나 빈 페이지를 생성할 경우 _pdfPage가 undefined되는 이슈 수정
Feat: 방향키 사용하여 페이지 이동 시 썸네일도 이동하도록 설정
- 방향키 사용하여 페이지 이동 시 썸네일, 스크롤도 같이 이동
=> [Fix, Feat] _pdfSize 이슈, 방향키 이동 로직 처리

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
현상: gesture로 필기를 숨긴 후 '필기 숨기기' 버튼으로 해제시 redraw가 안되던 현상
해결: redrawStroke를 하는 로직안에 pageInfo를 비교하는 구문이 있는데, 버튼으로 '필기 숨기기' 해제를 한 뒤에  pageInfo의 옳은 값이 넘어가지 않아서 발생. 따라서, 현재 rendering되고 있는 pageInfo의 값을 넘겨주기 위해 props의 pageInfo 값이 아닌 renderer의 pageInfo의 값을 넘겨준다.
=> [버그] 버튼으로 '필기 숨기기' 해제시 정상적으로 동작하지 않던 문제

src/nl-lib/common/util/functions.ts, src/nl-lib/renderer/penview/PenBasedRenderer.tsx
Fix: 펜 제스처로 페이지 이동 시 스크롤 이동, 썸네일 중앙 배열
- 펜 제스처로 상 하 이동 시 스크롤도 같이 이동하도록 변경
- 페이지 이동 시 썸네일은 중앙에 배치되도록 변경
=> [Fix] 펜 제스처로 페이지 이동 시 스크롤 이동, 썸네일 중앙 배열

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
문제 1. hideCanvasMode 상태에서 페이지 이동을 했을때, canvas가 사라지지 않는 현상(stroke가 다 보임)
- shouldComponentUpdate에서 hideCanvasMode 의 상태가 바뀔때만 해당 로직을 실행하기 때문에 페이지 이동과 같은 상태의 변화에서는 hideCanvasMode 로직이 실행되지 않음. 따라서, 조건을 변경하여 hideCanvasMode일때는 계속 지워주고, hideCanvasMode의 상태 false 로 변할때만 redraw 시켜준다.
문제 2. double tap stroke를 지워주는 로직에서 pageInfo를 잘못 넘겨주고 있던 버그
- double tap stroke를 지워주는 로직은 해당 제스처 로직을 다 끝낸 후 들어오게 된다. 문제는 페이지 이동이 됐을때 this.renderer.pageInfo와 같은 형태로 넘겨주면 탭을 지워주는 로직에서는 이동된 페이지의 pageInfo를 받게되는 것이다. 따라서, 제스처 로직이 발생되기 전의 pageInfo를 const로 선언하고 이 값을 넘겨주어 해결한다.
=> [버그] gesture 기능을 수행할 때 발생되는 버그 수정

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
1. 페이지가 없는 상태에서 '필기숨기기' 버튼 동작시 pageInfo undefined로 발생되는 오류 수정
2. dispath 하는 부분이 redraw를 수행하는 로직이기 때문에 제거한 라인과 중복이 됨. 따라서 제거
=> [버그수정] 필기 숨기기 버튼, 중복 로직 제거

src/nl-lib/common/mapper/MappingStorage.ts
내용 import를 하기 전에 함수를 사용하려는 버그. 추후 더 좋은 방향으로 app이 시작됨을 확인하고 동작하도록 수정해야 한다
=> BUGFIX] mapping storage 버그 - #375

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
1. 작업페이지에서 제스처와 관련된 동작은 한번 수행한 후 (탭 한번 터치, 대각선 중 하나를 긋기) 그리다보드 홈으로 이동 후 새페이지를 생성한다. 이때, 새페이지에서 이전에 했던 제스처동작을 이어서 할 경우 해당 제스처가 동작한다.
2. component 가 끝날때 제스처를 초기화해주지 못해 발생한 버그
=> #386 - 라이프사이클에 의한 제스처 초기화를 제대로 하지 못해 발생한 버그 수정

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
1. 현재 페이지에서 제스처를 위한 동작 중 하나를 수행하고 다른페이지로 이동해서 나머지 동작을 했을 때 제스처가 정상적으로 동작해버린다. 이를 막기 위해 페이지 이동시에도 제스처 관련 상태의 초기화가 이루어져야 한다.
=> #386 - 페이지 이동시 '필기 지우기'를 비롯한 '더블탭' 상태의 초기화가 이루어지지 않아 발생하는 버그 수정

src/nl-lib/renderer/penview/PenBasedRenderWorker.tsx
1. moveHoverPoint 로직에서 처음의 hover point를 변환된 값으로 잡아주지 못해 발생하는 버그이다. 따라서, 처음의 hover point를 변환된 dot의 x, y 값으로 설정해준다.
=> #393 - 플레이트와 노트를 동시에 사용할 때 hover point가 맞지 않는 버그 수정

src/nl-lib/renderer/penview/PenBasedRenderWorker.tsx
1. 플레이트로 페이지 생성 후 사용
2. 바로 노트를 이용하여 새로운 페이지 생성 후 펜을 사용
3. hover point가 맞지 않음
PenBaseRendererWorker.moveHoverPoint()에서 isPlatePage를 사용하여 현재 작업하는 pageInfo가 플레이트 인지 아닌지를 확인한다.
이때, 위의 순으로 진행시 노트에서 필기 하고 있지만 노트 페이지의 pageInfo가 아니라 플레이트의 pageInfo가 사용되고 있는 것을 확인하였다.
이유는 moveHover안의 isPlatePage()에서 this.currentPageInfo를 사용하고 있는데 이 부분이 제대로 업데이트가 되고 있지 않았다.
이를 해결하기 위해 changePage()에서 this.currentPageInfo 또한 업데이트 해줄 수 있도록 수정하였다.
=> #393 - 플레이트 -> 노트 순으로 필기시 (노트 페이지로 이동 발생) hover point가 맞지 않는 버그 수정

src/nl-lib/renderer/penview/PenBasedRenderWorker.tsx
문제상황:
1. pdf를 annotation한 뒤 각각 페이지에 stroke를 그린다.
2. 제스처로 페이지 이동시 직전 작업페이지의 stroke가 첫번째 thumbnail 뷰에 redraw 된다.
3. 이러한 문제는 doubleTap stroke를 지우기 위해 redraw로직을 dispatch하는데 이때 pageInfo가 undefined로 들어오면서 발생
4. 정리: pageInfo가 undefined로 들어올 때, 첫번째 thumbnail이 redraw되면서 직전 작업페이지의 stroke를 그려준다.
첫번째 접근방법,
 [redrawStrokes()안에 있는 this.pageInfo === undefined를 제거하면 되지 않을까?]
- 첫번째 thumbnail이 redraw 로직을 타지 않아 stroke가 따로 들어오지는 않으나 첫번째 thumbnail 페이지 회전 시 stokre가 회전하지 않는다.
- 9c2678e0e3165c42796acabe6b656cededd156d1커밋 참고
두번째 접근방법,
 [this.pageInfo === undefined를 가지면서 첫번째 thumbnail에서만 회전할 수 있도록 조건을 추가]
- 즉, undefined로 들어올 때, 작업페이지가 첫번째(0)인 thumbnail인 경우에만 redraw로직을 타게 하면 회전문제 또한 해결된다.
- 따라서, activePageNo가 0이고, redraw로 들어오는 pageInfo가 activePageNo와 같은 0일때만 redraw를 타게 수정한다.
=> [버그] 페이지이동/회전 동작 시 첫번째 thumbnail의 stroke가 잘못 redraw되는 버그 수정

public/nproj/note_3_1013_1.nproj, src/GridaBoard/Load/ConvertFileLoad.tsx
Fix: PDF로 생성된 보드에 마우스 스트로크 생성 시 새 페이지 생성되는 문제 수정
- /list 파일로 보드 생성을 PDF로 할 경우, 해당 보드에서 마우스로 첫 스트로크 그릴 시 PDF 페이지가 아닌,
새 페이지 자동 생성 후, 해당 페이지에 첫 스트로크가 그려지는 이슈
- 파일로 보드 생성을 PDF로 할 경우, 로딩 서클이 생성되지 않는 이슈
- history path 코드를 최상단으로 옮기고, 잘못된 파일 불러올 경우에는 해당 페이지 이동을 /list 페이지로 대체하여 이동 방지
- 기타 사항으로, 파일명이 ' . ' 으로 시작하는 경우 수정
Fix: PUI 색상 데이터 수정
- 중복된 # 제거
=> [버그] PDF로 생성된 보드에 마우스 스트로크 생성 시 새 페이지 생성되는 문제 수정

src/nl-lib/renderer/penview/PenBasedRenderWorker.tsx
문제상황:
전체 페이지가 줄었을때(페이지가 삭제되었을때) redraw가 발생하는 데(* PenBaseRenderer.tsx -> shouldComponentUpdate 358번째 줄) 이때 페이지가 1개 존재하다가 삭제되면 activePage는 undefined가 되기 때문에 이 후의 로직을 진행하면 오류페이지가 발생한다.
따라서, 이를 해결하기 위해 activePage가 존재하지 않을 경우 redraw를 종료시켜준다.
=> Fix: 07f3642 커밋 수정으로 인한 activePage가 undefined일 때 발생하는 버그 수정

src/boardList/layout/component/mainContent/GridView.tsx
Fix: 보드 리스트 정렬 방식 변경 시 썸네일 미갱신 수정
=> [버그] 보드 리스트 정렬 방식 변경 시 썸네일 미갱신 수정

src/GridaBoard/components/buttons/RotateButton.tsx, src/nl-lib/renderer/penview/PenBasedRenderer.tsx
기존내용에서 수정내용으로 회전 시 심볼 표시 조건을 변경하였습니다.
기존내용: 
부기보드 내에서 제스처로 회전을 할 시 무조건 화면에 심볼이 나타나도록 한다.
수정내용:
회전을 한 뒤 부기보드를 터치하면 심볼이 나타나도록 한다. * 한번만 허용
=> [심볼] 회전시 심볼이 표시되는 조건 변경

src/GridaBoard/View/Drawer/PersistentDrawerRight.tsx
1. newPage 이미지 크기 수정 
2. 기존의 dashed dot에서 liner gradient 적용한 dot으로 변경
3. '+' -> material plus icon 사용할 수 있도록 수정
4. page 목록 맨 아래에 보이는 흰색 liner 제거
=> [UI] newPage 이미지 크기 수정 및 dot 변경, 목록 맨 밑 흰색 liner 제거

src/boardList/BoardList.tsx, src/boardList/layout/component/dialog/detail/MoveDialog.tsx
Feat: 그룹 삭제 등 카테고리 변화 시 변경사항 MainContent에 미반영 수정
- 그룹 삭제, 그룹 이름 변경 등 카테고리 변화가 발생할 경우 MainContent에 반영되도록 updateCount 추가 변경
- 그룹 삭제 시, 해당 그룹 내 보드들이 기본 그룹으로 이동하는 것을 바로 인지할 수 있도록, 기본 그룹 으로 카테고리 이동
Feat: 보드 이동 dialog 상 Unshelved 표시 수정
- 선택한 보드의 그룹 이동 시의 dialog 상에 기본 그룹이 Unshelved로 표시되는 부분 수정
=> [Feat] 그룹 카테고리 변화 시 MainContent에 즉각 반영, 보드 이동 Dialog 텍스트 수정

src/GridaBoard/KeyBoardShortCut.ts, src/nl-lib/common/util/functions.ts
Feat: 포커스 이동에 따른 썸네일 이동 함수 보장
- 마우스로 보드나 썸네일을 클릭하여 해당 영역의 스크롤이 활성화 상태가 될 경우,
키보드 클릭에 따른 scrollIntoView의 스크롤 제어권을 잃게 되므로 preventDefault 추가
=> Feat: 포커스 이동과 무관하게 scrollToThumbnail 함수 수행 보장

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
기존내용에서 수정내용으로 심볼 display 로직을 수정함.
기존내용: 
페이지 이동/회전과 같은 상태 변화 후 플레이트 첫 터치시 보여질 수 있도록 함
수정내용: 
조건없이 심볼이 항상 보여질 수 있도록 함
<추가내용>
이후 심볼의 보여지는 조건을 다시 정의할 수 있어 기존의 심볼 timer 및 show/hide 함수는 주석처리 하였습니다.
상태 변화로 연달아 발생하는 toast 메세지는 최신의 메시지 한개만 보여질 수 있도록 기존의 toast 메세지는 사라지도록 수정하였습니다.
------------------------------------------------------
테스트 도중 버그 발견하여 수정 업데이트 합니다. 충돌로 인해 해당 브렌치에 이어서 작업합니다.
발생내용: 플레이트 -> 종이 사용시 (종이 pdf 생성) 종이를 plate로 인식하며 hoverPoint가 맞지 않는 현상
- onLivePenPageInfo() 안에서 isRun 플래그를 사용하는데(심볼 때문에 정의 #428 ) 이로 인해, 
플레이트 -> Ncode 종이 사용시 registerPageInfoForPlate, onNcodePageChanged 로직을 정상적으로 타지 못함.
결국 pageInfo를 업데이트 하지 못함.
- isRun은 심볼을 보여주기 위한 조건으로 사용되는 플래그임. 따라서, 해당 플래그 조건을 안쪽으로 옮겨준다.
=> [심볼/버그] 심볼이 항상 보여지도록 수정, 플레이트<->종이 사용시 hoverPoint 맞지 않는 버그

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
조건을 추가하여 플레이트 사용시에만 symbol이 항상 뜨도록 설정합니다.
=> [심볼] 종이, 플레이트 관계없이 심볼이 항상 뜨는 현상

src/boardList/BoardListPageFunc.tsx
Fix: 저장하기(덮어쓰기) 시 보드 리스트의 썸네일 표시 이슈 수정
- 발생 이슈 1 : 페이지 삭제 후 덮어쓰기 시, 마지막 페이지가 썸네일로 표시되는 이슈
- 발생 이슈 2 : 2장 연속 삭제 후 덮어쓰기 시, PDFDocument has no pages so `PDFDocument.removePage` cannot be called 에러
- 발생 이슈 3 : 0 번 페이지 아닌 페이지 포함하여, 2장 연속 삭제 후 덮어쓰기 시,
Unhandled Rejection (Error): `index` must be at least 0 and at most 0, ~ 에러
- 발생 이슈 4 : 새 페이지 생성 후 덮어쓴 뒤, 해당 보드 재차 불러오고 저장된 새 페이지 삭제 시 후 덮어쓰기 시, 3번과 동일 에러
---
- docPages 내의 모든 page가 [NeoPdfDocument - deletePage] 함수의 결과로 동일한 removedPage 배열을 가지고 있다.
- removedPage의 배열을 forEach로 탈 때마다 페이지가 삭제되고, pageCache를 통해 페이지 수를 갱신시킨다.
- 재차 for of를 통해 불려온 다음 page가 동일한 removedPage 배열로, 갱신되어 줄어든 페이지에 적용해 페이지를 삭제한다.
- 즉, pdfDoc의 페이지는 줄어드는데, docPages의 모든 page가 같은 removedPage 배열로 삭제를 수행하여 이슈가 발생한 것
---
- removedPage는 어느 page든 동일하므로 단 한번만 수행하도록 수정
=> Fix: 저장하기(덮어쓰기) 시 보드 리스트의 썸네일 표시 이슈 수정
