src/GridaBoard/Buttons/ButtonLayerBottom.tsx, src/GridaBoard/Buttons/ButtonLayerSide.tsx, src/GridaBoard/Buttons/ButtonLayer_forTest.tsx, src/GridaBoard/Load/LoadGrida.tsx, src/GridaBoard/Save/SavePdfDialog.tsx, src/components/buttons/BackgroundButton.tsx, src/nl-lib/ncodepod/NcodePrint/Dialogs/OptionDialog.tsx
위쪽 layer 불필요한 부분 제거 및 icon 변경 작업
=> svgIcon hover / grida 파일 icon변경 / 위쪽 layer 제거

src/GridaBoard/View/Drawer/PersistentDrawerRight.tsx, src/boardList/BoardListPageFunc.tsx
Feat : 최초화면(대기상태)일 때 왼쪽 레이어에 새 페이지 생성하는 + 박스 생성
-> 그리다보드를 시작할 때 numDocPages가 0이면 해당 박스가 생성.
-> 만약 빈페이지를 생성한 후 해당 페이지 삭제할 경우 다시 해당 박스 생성.
=> Feat: 최초 화면 (대기상태)일 때 왼쪽 레이어에 새 페이지 생성하는 + 박스 생성

src/GridaBoard/GridaApp.ts, src/GridaBoard/GridaDoc.ts, src/nl-lib/common/noteserver/SurfaceInfo.ts, src/nl-lib/common/penstorage/InkStorage.ts, src/nl-lib/renderer/penview/PenBasedRenderer.tsx
Feat: 최초화면(대기화면) 일 때 Plate 터치 시 가로형 A4 생성(270도 ver.)
- Plate일 경우 A4_더미 생성 후 270도 회전하여 생성
=> Feat: 최초화면(대기화면) 일 때 Plate 터치 시 가로형 A4 생성(270도 ver.)

src/boardList/layout/component/dialog/detail/GestureDialog.tsx
Fix: 제스처 Dialog 조건 변경
- [더 알아보기] 클릭 시 dialog 닫히도록 수정
=> [Fix] 제스처 Dialog 조건 변경

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
1. 심볼터치로 새페이지를 생성했을때 가로로 보여질 수 있도록 rotation 적용
추가.
직전 작업페이지의 landscape/portrait 를 구별하여 페이지 각도 설정하는 로직 주석처리
=> [업데이트] 심볼터치로 새페이지 생성하는 로직

src/boardList/layout/component/mainContent/GridView.tsx
휴지통 내 표시되는 기본 카테고리명 'Unselved'를 '기본 그룹'으로 뜨도록 수정
=> [Fix] 휴지통 내 기본  카테고리명 표시 수정

src/GridaBoard/Load/ConvertFileLoad.tsx
Fix: 파일 생성 조건 외에 불러올 수 없는 것 추가 수정
- #409 추가 검토 사안으로 올라온, 아직 'test!!@#.pptx' 열린다는 안건 확인 후 수정
=> #409 - 파일 생성 조건 외에 불러올 수 없는 것 추가 수정

src/GridaBoard/View/Drawer/ThumbnailItem.tsx
1. page 목록에 보여지는 hideCanvasIcon 크기 수정 * 65px -> 40px
=> [UI] page 목록에 보여지는 hideCanvasIcon 크기 수정

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
기존내용에서 수정내용으로 시간 재설정함
기존내용: 3s
수정내용: 10s
=> [심볼] Symbol이 보여졌다가 사라지는 delay 시간 수정

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
1. 심볼 터치로 인한 페이지 생성 제스처 기능은 부기보드(plate3)에서만 가능하도록 수정
2. 제스처로 새페이지 생성시 직전 작업페이지와 동일한 형태로 생성 될수 있도록 수정
- 새페이지 생성시 직전 작업페이지의 rotation 값을 더해줌으로써 동일한 형태로 만들어준다.
=> [제스처] 제스처로 인한 페이지 생성 수정사항 업데이트

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
기존내용에서 수정내용으로 제스처 영역을 재설정함.
기존내용: 
짧은면 기준으로 1/3 영역을 정사각형 형태로 설정
수정내용:
너비는 짧은면 기준 1/3, 높이는 짧은면 기준 1/5 으로 설정
=> [제스처] 제스처 영역 재설정

src/GridaBoard/components/PUIController.ts
Feat: PUI 페이지 이동 시 썸네일 스크롤 이동 추가
- PUI 페이지 이동 시 썸네일 스크롤 중앙 이동
=> Feat: PUI 페이지 이동 시 썸네일 스크롤 이동 추가

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
1. 심볼 timer 수정
- 기존의 심볼을 안보이게 하는 timer는 symbolUp이 실행될 때마다 쌓이게 되어 버그를 발생시킴. 
예) 페이지 이동/회전과 같은 변화를 10초 이내 여러번 하면 10초 뒤부터 hideSymbol()이 여러번 실행됨. -> timer가 제대로 동작X
- 따라서, 한개의 timer를 정의하고 해당 timer를 동작시켜 심볼을 사라지게 해야한다. 
- 또한, symbolUp이 실행된 후 10초 이내 symbolUp 로직이 또 실행될 경우 timer를 clear 해줌으로써 이전의 timer 상태를 없애준다.
2. 플레이트<->종이(Ncode)/회전/이동과 같은 상태변화일 때 Symbol(toast포함)이 안보여질 수 있도록 초기화 시켜준다.
=> [심볼] 심볼 타이머 수정 및 변화에 따른 심볼 disaplay 재설정

src/GridaBoard/components/PUIController.ts
Feat: PUI의 add_page 시 현재 페이지 각도 적용
- '+' 심볼의 로직과 동일
=> [PUI] add_page 시 현재 페이지 각도 적용

src/nl-lib/neosmartpen/pencomm/pencomm.ts, src/nl-lib/renderer/penview/PenBasedRenderWorker.tsx
원인1. 리스트로 가기등, 여타 이유로 그리다보드 내부의 값 초기화
원인2. hover 모드시 page Info가 변경되지 않으면 따로 info를 추가로 보내주지 않음
이 두가지 원인으로 인해 SOBP를 가지고 있지 않은 상태에서 hover 모드가 넘어올 때도 있음
=> hover 모드시 pageInfo가 안올때 처리

src/nl-lib/renderer/penview/PenBasedRenderer.tsx
#453 - Plate용 Symbol 통한 페이지 생성 시 스크롤 미이동 수정
=> #453 - Plate용 Symbol 통한 페이지 생성 시 스크롤 미이동 수정

src/GridaBoard/components/buttons/RotateButton.tsx
#450 - 키보드 단축키 TAB 시 마우스 클릭 등 외부 입력 전까지 회전하지 않는 이슈 수정
=> #450 - 키보드 단축키 TAB 시 미회전 이슈

src/GridaBoard/components/buttons/RotateButton.tsx
Fix: 키보드 단축키 TAB 시 미회전 이슈 추가 수정
- 썸네일 페이지 미회전 사항으로 재차 수정
=> Fix: 키보드 단축키 TAB 시 미회전 이슈 추가 수정

src/GridaBoard/Load/ConvertFileLoad.tsx, src/GridaBoard/client/pages/GridaBoard.tsx
- 공통: (),{},[] 추가
- 맥 : 텍스트 들어왔을때 NFC로 수정
=> HOTFIX] 파일명 소,중,대괄호 추가, 맥 한글 버그 수정

README.md, package.json, src/GridaBoard/Save/SavePdf.tsx
pdf가 없는 npaper일 경우, pdf로 만들때 방향을 따로 설정을 안해줘서 발생한 이슈
=> [HOTFIX] 가로모드 npaper를 사용하여 페이지 생성시 pdf로 내보내기 이슈
